enhance: genarate agent version

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -10,12 +10,10 @@ on:
       - v[0-9]+.[0-9]+.[0-9]+
       - v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+
       - v[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+
-
   workflow_dispatch:
-  
 jobs:
   init-variable:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     outputs:
       container_tag: ${{ steps.init_variable.outputs.container_tag }}
     steps:
@@ -33,26 +31,40 @@ jobs:
             VERSION=$(git describe --tags --abbrev=8)
           fi
           echo "container_tag=${VERSION}" >> $GITHUB_OUTPUT
-
+  check-generate-versions:
+    runs-on: ubuntu-24.04
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - name: check generate versions diff
+        id: check-versions-diff
+        run: |
+          make update-agents-version
+          if ! git diff HEAD --exit-code > /dev/null; then
+            echo "Error: Detected changes after running 'make update-agents-version'."
+            echo "The following changes were detected:"
+            git diff HEAD
+            echo "Please run 'make update-agents-version' and commit the changes."
+            exit 1
+          fi
   manifest-conformance:
-    runs-on: ubuntu-latest
+    needs: [check-generate-versions]
+    runs-on: ubuntu-24.04
     steps:
       - name: Checkout
         uses: actions/checkout@v4
-
       - name: Install Helm
         uses: azure/setup-helm@v3
-
       - name: Validate Helm Policy
-        run: |
-          OUTPUT=github make conftest 
-
+        run: "OUTPUT=github make conftest \n"
   build-jenkins:
     permissions:
       contents: read
       packages: write
     needs: [init-variable, manifest-conformance]
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - name: checkout
         uses: actions/checkout@v4
@@ -79,7 +91,6 @@ jobs:
             ${{ secrets.DOCKER_USERNAME }}/jenkins:latest
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
   build-jenkins-agent-base:
     permissions:
       contents: read
@@ -87,8 +98,8 @@ jobs:
     needs: [init-variable, manifest-conformance]
     strategy:
       matrix:
-        os: ["centos","ubuntu"]
-    runs-on: ubuntu-latest
+        os: ["centos", "ubuntu"]
+    runs-on: ubuntu-24.04
     steps:
       - name: checkout
         uses: actions/checkout@v4
@@ -138,22 +149,19 @@ jobs:
             DISTRIBUTION_SUFFIX=${{ steps.step-variable.outputs.distribution }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
-
   build-deprected-agent-centos:
-    needs: [ build-jenkins-agent-base, init-variable ]
+    needs: [build-jenkins-agent-base, init-variable]
     uses: ./.github/workflows/build_centos.yaml
     secrets: inherit
     with:
       container_tag: ${{ needs.init-variable.outputs.container_tag }}
-
   build-agent-nodejs:
     needs: [build-jenkins-agent-base, init-variable]
     strategy:
       matrix:
         runtime: [docker, podman]
-        version: ["16.17.0", "18.20.4", "20.16.0"]
-    runs-on: ubuntu-latest
+        version: [16.17.0, 18.20.4, 20.16.0]
+    runs-on: ubuntu-24.04
     env:
       os: ubuntu
     steps:
@@ -195,14 +203,13 @@ jobs:
             DISTRIBUTION_SUFFIX=-${{ env.os }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
   build-agent-python:
     needs: [build-jenkins-agent-base, init-variable]
     strategy:
       matrix:
-        runtime: [ docker, podman ]
-        version: [ "2.7.9", "3.8.19", "3.10.9", "3.11.9" ]
-    runs-on: ubuntu-latest
+        runtime: [docker, podman]
+        version: [3.8.19, 2.7.9, 3.10.9, 3.11.9]
+    runs-on: ubuntu-24.04
     env:
       os: ubuntu
     steps:
@@ -244,63 +251,61 @@ jobs:
             DISTRIBUTION_SUFFIX=-${{ env.os }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
-  build-agent-go:
-    needs: [ build-jenkins-agent-base, init-variable ]
-    strategy:
-      matrix:
-        runtime: [ docker, podman ]
-        version: [ "1.17.13", "1.18.10", "1.20.14", "1.22.6"]
-    runs-on: ubuntu-latest
-    env:
-      os: ubuntu
-    steps:
-        - name: checkout
-          uses: actions/checkout@v4
-        - name: Set up QEMU
-          uses: docker/setup-qemu-action@v3
-        - name: Login to ghcr.io
-          uses: docker/login-action@v2
-          with:
-            username: ${{ secrets.DOCKER_USERNAME }}
-            password: ${{ secrets.DOCKER_PASSWORD }}
-        - name: init variables
-          id: step-variable
-          run: |
-            export "runtime=$([ ${{ matrix.runtime }} == podman ] && (echo -podman))"
-            echo "runtime=${runtime}" >> $GITHUB_OUTPUT
-            export "goVersion=$( echo -${{ matrix.version }})"
-            echo "suffix=${goVersion}-${os}${runtime}" >> $GITHUB_OUTPUT
-        - name: use setup-buildx-action
-          uses: docker/setup-buildx-action@v3
-        - name: build jenkins agent with go
-          uses: docker/build-push-action@v6
-          with:
-            context: .
-            file: ./jenkins-agent/go/Dockerfile
-            github-token: ${{ secrets.GITHUB_TOKEN }}
-            push: true
-            provenance: false
-            platforms: linux/amd64, linux/arm64
-            tags: |
-              ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-go:${{ needs.init-variable.outputs.container_tag }}${{ steps.step-variable.outputs.suffix }}
-              ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-go:latest${{ steps.step-variable.outputs.suffix }}
-            build-args: |
-              REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
-              RUNTIME=${{ steps.step-variable.outputs.runtime }}
-              VERSION=${{ matrix.version }}
-              DISTRIBUTION=${{ env.os }}
-              DISTRIBUTION_SUFFIX=-${{ env.os }}
-            cache-from: type=gha
-            cache-to: type=gha,mode=max
-
-  build-agent-maven:
-    needs: [ build-jenkins-agent-base, init-variable ]
+  build-agent-golang:
+    needs: [build-jenkins-agent-base, init-variable]
     strategy:
       matrix:
         runtime: [docker, podman]
-        version: [8, 11, 17, 21]
-    runs-on: ubuntu-latest
+        version: [1.22.6, 1.17.13, 1.18.10, 1.20.14]
+    runs-on: ubuntu-24.04
+    env:
+      os: ubuntu
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      - name: Login to ghcr.io
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: init variables
+        id: step-variable
+        run: |
+          export "runtime=$([ ${{ matrix.runtime }} == podman ] && (echo -podman))"
+          echo "runtime=${runtime}" >> $GITHUB_OUTPUT
+          export "goVersion=$( echo -${{ matrix.version }})"
+          echo "suffix=${goVersion}-${os}${runtime}" >> $GITHUB_OUTPUT
+      - name: use setup-buildx-action
+        uses: docker/setup-buildx-action@v3
+      - name: build jenkins agent with go
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: ./jenkins-agent/go/Dockerfile
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          push: true
+          provenance: false
+          platforms: linux/amd64, linux/arm64
+          tags: |
+            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-go:${{ needs.init-variable.outputs.container_tag }}${{ steps.step-variable.outputs.suffix }}
+            ${{ secrets.DOCKER_USERNAME }}/jenkins-agent-go:latest${{ steps.step-variable.outputs.suffix }}
+          build-args: |
+            REGISTRY_REPO=${{ secrets.DOCKER_USERNAME }}
+            RUNTIME=${{ steps.step-variable.outputs.runtime }}
+            VERSION=${{ matrix.version }}
+            DISTRIBUTION=${{ env.os }}
+            DISTRIBUTION_SUFFIX=-${{ env.os }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+  build-agent-maven:
+    needs: [build-jenkins-agent-base, init-variable]
+    strategy:
+      matrix:
+        runtime: [docker, podman]
+        version: ["8", "11", "17", "21"]
+    runs-on: ubuntu-24.04
     env:
       os: ubuntu
     steps:
@@ -345,37 +350,32 @@ jobs:
             DISTRIBUTION_SUFFIX=-${{ env.os }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
-
   e2e:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     if: github.ref_type != 'tag'
-    needs: [ init-variable, build-jenkins ]
+    needs: [init-variable, build-jenkins]
     steps:
       - name: checkout
         uses: actions/checkout@v4
-
       - name: Set up Helm
         uses: azure/setup-helm@v3
         with:
           version: v3.12.1
-
       - name: Create kind cluster
         uses: helm/kind-action@v1.7.0
-
       - name: Deploy Chart
         run: |
           ./hack/install/envsubst.sh
           VERSION=${{ needs.init-variable.outputs.container_tag }} make deploy
-
   publish-chart:
     if: startsWith(github.ref, 'refs/tags/v')
-    needs: [ build-jenkins, build-agent-maven, build-agent-go, build-agent-python, build-agent-nodejs ]
+    needs: [build-jenkins, build-agent-maven, build-agent-golang, build-agent-python, build-agent-nodejs]
     permissions:
       contents: write
     env:
       HELM_CHARTS_DIR: charts
       HELM_CHART_NAME: jenkins
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -388,29 +388,20 @@ jobs:
         run: |
           VERSION=${GITHUB_REF#refs/tags/}
           echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
-
       - name: Tag helm chart image
         run: |
           image_tag=${{ steps.get_version.outputs.VERSION }}
           chart_version=${{ steps.get_version.outputs.VERSION }}
           sed -i "s/latest/${image_tag}/g" $HELM_CHARTS_DIR/values.yaml
-          
-          # update relok8s_images by language versions matrix.
-          echo "updating relok8s_images ...."
-          ./hack/update_relok8s_images.sh $HELM_CHARTS_DIR/values.yaml $HELM_CHARTS_DIR/.relok8s-images.yaml
-          sed -i "s/latest/${image_tag}/g" $HELM_CHARTS_DIR/.relok8s-images.yaml
-          cat $HELM_CHARTS_DIR/.relok8s-images.yaml
-          
           chart_smever=${chart_version#"v"}
           sed -i "s/0.1.0/${chart_smever}/g" $HELM_CHARTS_DIR/Chart.yaml
-
       - uses: getsentry/action-github-app-token@v2
         id: get_app_token
         with:
-            app_id: ${{ secrets.APP_ID }}
-            private_key: ${{ secrets.APP_PRIVATE_KEY }}
+          app_id: ${{ secrets.APP_ID }}
+          private_key: ${{ secrets.APP_PRIVATE_KEY }}
       - name: Sync Chart Repo
-        run: |
+        run: |-
           git config --global user.email "amamba[bot]@users.noreply.github.com"
           git config --global user.name "amamba[bot]"
           git clone https://x-access-token:${{ steps.get_app_token.outputs.token }}@github.com/amamba-io/charts.git amamba-charts
