add minimal chart

diff --git a/.github/workflows/check_relok8s.yaml b/.github/workflows/check_relok8s.yaml
--- a/.github/workflows/check_relok8s.yaml
+++ b/.github/workflows/check_relok8s.yaml
@@ -10,7 +10,8 @@ jobs:
       SOURCE_CONTAINER_REGISTRY: http://localhost:8080
       TARGET_CONTAINER_REGISTRY: http://localhost:8081
       TEST_CONTAINER_REGISTRY: k8s.container.registry.io
-      HELM_CHARTS_DIR: charts
+      HELM_CHARTS_DIR: charts/jenkins-full
+      HELM_CHARTS_NAME: jenkins-full
     steps:
       - name: checkout
         uses: actions/checkout@v4
@@ -37,7 +38,7 @@ jobs:
       - name: Install chart-syncer
         run: |
           helm plugin install https://github.com/chartmuseum/helm-push.git
-          wget -q "https://files.m.daocloud.io/github.com/DaoCloud/charts-syncer/releases/download/v${{ env.CHARTS_SYNCER_VERSION }}/charts-syncer_${{ env.CHARTS_SYNCER_VERSION }}_linux_x86_64.tar.gz"
+          wget --tries=5 --retry-connrefused --wait=5 -q "https://files.m.daocloud.io/github.com/DaoCloud/charts-syncer/releases/download/v${{ env.CHARTS_SYNCER_VERSION }}/charts-syncer_${{ env.CHARTS_SYNCER_VERSION }}_linux_x86_64.tar.gz"
           tar -zvxf charts-syncer_${{ env.CHARTS_SYNCER_VERSION }}_linux_x86_64.tar.gz
           chmod +x charts-syncer &&  mv charts-syncer /usr/local/bin/
       - name: Update chart tag
@@ -53,7 +54,7 @@ jobs:
       - name: Push Helm Chart to Source ChartMuseum
         run: |
           helm repo add source-chartmuseum ${{ env.SOURCE_CONTAINER_REGISTRY }}
-          helm cm-push ./amamba-charts/docs/jenkins-${{ steps.init-variable.outputs.CHART_SMEVER }}.tgz source-chartmuseum
+          helm cm-push ./amamba-charts/docs/${{ env.HELM_CHARTS_NAME }}-${{ steps.init-variable.outputs.CHART_SMEVER }}.tgz source-chartmuseum
       - name: Sync charts using Chart-Syncer
         run: |
           cat <<EOF > syncer-config.yaml
@@ -69,7 +70,7 @@ jobs:
               kind: "CHARTMUSEUM"
               url: ${{ env.TARGET_CONTAINER_REGISTRY }}
           charts:
-            - name: jenkins
+            - name: ${{ env.HELM_CHARTS_NAME }}
               versions:
                 - ${{ steps.init-variable.outputs.CHART_SMEVER }}
           EOF
@@ -81,17 +82,17 @@ jobs:
           helm repo add target-chartmuseum ${{ env.TARGET_CONTAINER_REGISTRY }}
           helm repo update
           chart_smever=${{ steps.init-variable.outputs.CHART_SMEVER }}
-          helm search repo target-chartmuseum/jenkins --version $chart_smever || exit 1
-          IMAGE_LIST=`helm template test target-chartmuseum/jenkins --version $chart_smever | grep "image: " | awk -F'[: "]+' '{print $3":"$4}' | sort | uniq`
+          helm search repo target-chartmuseum/${{ env.HELM_CHARTS_NAME }} --version $chart_smever || exit 1
+          IMAGE_LIST=`helm template test target-chartmuseum/${{ env.HELM_CHARTS_NAME }} --version $chart_smever | grep "image: " | awk -F'[: "]+' '{print $3":"$4}' | sort | uniq`
           if [ -z "${IMAGE_LIST}" ] ; then 
-              echo "error, failed to find image from chart template for jenkins" 
+              echo "error, failed to find image from chart template for ${{ env.HELM_CHARTS_NAME }}" 
               exit 1 
           else 
-            echo "found image from jenkins chart template: ${IMAGE_LIST} "
+            echo "found image from ${{ env.HELM_CHARTS_NAME }} chart template: ${IMAGE_LIST} "
             for IMAGE in ${IMAGE_LIST} ; do
               echo image: ${IMAGE}
               if [[ ${IMAGE} != ${{ env.TEST_CONTAINER_REGISTRY }}* ]] ; then 
-                  echo "error, failed to check image ${IMAGE} from chart template for jenkins, because the image registry has not been replaced"
+                  echo "error, failed to check image ${IMAGE} from chart template for ${{ env.HELM_CHARTS_NAME }}, because the image registry has not been replaced"
                   exit 1
               fi
             done
@@ -100,7 +101,7 @@ jobs:
               echo image: ${IMAGE}
               LEN=`echo ${IMAGE} | awk -F '/' '{print NF}'` 
               if [[ ${LEN} -lt 3 ]] ; then 
-                  echo "error, failed to check image ${IMAGE} from chart template for jenkins, because the image does not have repository" 
+                  echo "error, failed to check image ${IMAGE} from chart template for ${{ env.HELM_CHARTS_NAME }}, because the image does not have repository" 
                   exit 1 
               fi
             done 
